---
- id: CMD-0040
  key: kubeletEventQpsArgumentSet
  title: kubelet --event-qps argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep ' --event-qps' |
    grep -o ' --event-qps=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - rke2
