---
- id: CMD-0032
  key: kubeletAnonymousAuthArgumentSet
  title: kubelet --anonymous-auth argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" 'BEGIN {n=split(bin, parts, " ")}
    {name=$1; sub(/^.*\//, "", name); if (!n || name != parts[1]) next;
    for (i=2; i<=n; i++) if ($i != parts[i]) next; print}' |
    grep ' --anonymous-auth' |
    grep -o ' --anonymous-auth=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - eks
    - rke2
