---
- id: CMD-0024
  key: kubeconfigFileExistsPermissions
  title: Kubeconfig file exists ensure permissions
  nodeType: worker
  audit: >-
    output=`stat -c %a $(ps -eo args |
    awk -v bin="$proxy.bins" 'BEGIN {n=split(bin, parts, " ")}
    {name=$1; sub(/^.*\//, "", name); if (!n || name != parts[1]) next;
    for (i=2; i<=n; i++) if ($i != parts[i]) next; print}' |
    grep 'kubeconfig' |
    grep -o 'kubeconfig=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1') 2>/dev/null` || echo $output
  platforms:
    - k8s
    - rke2
