---
- id: CMD-0042
  key: kubeletTlsPrivateKeyFileArgumentSet
  title: kubelet --tls-private-key-file argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep ' --tls-private-key-file' |
    grep -o ' --tls-private-key-file=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - rke2
