---
- id: CMD-0025
  key: kubeconfigFileExistsOwnership
  title: Kubeconfig file exists ensure ownership
  nodeType: worker
  audit: >-
    output=`stat -c %U:%G $(ps -eo args |
    awk -v bin="$proxy.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep 'kubeconfig' |
    grep -o 'kubeconfig=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1') 2>/dev/null` || echo $output
  platforms:
    - k8s
    - rke2
