---
- id: CMD-0044
  key: kubeletRotateKubeletServerCertificateArgumentSet
  title: kubelet RotateKubeletServerCertificate argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep 'RotateKubeletServerCertificate' |
    grep -o 'RotateKubeletServerCertificate=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - eks
    - rke2
