---
- id: CMD-0037
  key: kubeletProtectKernelDefaultsArgumentSet
  title: kubelet --protect-kernel-defaults argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep ' --protect-kernel-defaults' |
    grep -o ' --protect-kernel-defaults=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - rke2
