---
- id: CMD-0038
  key: kubeletMakeIptablesUtilChainsArgumentSet
  title: kubelet --make-iptables-util-chains argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep ' --make-iptables-util-chains' |
    grep -o ' --make-iptables-util-chains=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - eks
    - rke2
