---
- id: CMD-0034
  key: kubeletClientCaFileArgumentSet
  title: kubelet --client-ca-file argument is set
  nodeType: worker
  audit: >-
    ps -eo args |
    awk -v bin="$kubelet.bins" '{name=$1; sub(/^.*\//, "", name); if (name == bin) print}' |
    grep ' --client-ca-file' |
    grep -o ' --client-ca-file=[^"]\S*' |
    awk -F "=" '{print $2}' |
    awk 'FNR <= 1'
  platforms:
    - k8s
    - eks
    - rke2
